name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install numpy numba jax torch
      - name: Benchmark oriented-object
        run: |
          cd jit
          python run.py
      - name: Benchmark functional
        run: |
          cd jit
          python run_func.py
